name: manage-azure-policy-6c2adb0d
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/KeyVault_SoftDelete_should_be_enabled_Append-KV-SoftDelete/**'
#      - 'policies/Application_Gateway_should_be_deployed_with_WAF_enabled_Deny-AppGW-Without-WAF/**'
#      - 'policies/Deny_the_creation_of_public_IP_Deny-PublicIP/**'
#      - 'policies/RDP_access_from_the_Internet_should_be_blocked_Deny-RDP-From-Internet/**'
#      - 'policies/Subnets_should_have_a_Network_Security_Group_Deny-Subnet-Without-Nsg/**'
#      - 'policies/Subnets_should_have_a_User_Defined_Route_Deny-Subnet-Without-Udr/**'
#      - 'policies/Deploy_a_default_budget_on_all_subscriptions_under_the_assigned_scope_Deploy-Budget/**'
#      - 'policies/Deploy_a_route_table_with_specific_user_defined_routes_Deploy-Custom-Route-Table/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Application_Gateway_to_Log_Analytics_workspace_Deploy-Diagnostics-ApplicationGateway/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_ExpressRoute_to_Log_Analytics_workspace_Deploy-Diagnostics-ExpressRoute/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Firewall_to_Log_Analytics_workspace_Deploy-Diagnostics-Firewall/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Load_Balancer_to_Log_Analytics_workspace_Deploy-Diagnostics-LoadBalancer/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Network_Security_Groups_to_Log_Analytics_workspace_Deploy-Diagnostics-NetworkSecurityGroups/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Network_Interfaces_to_Log_Analytics_workspace_Deploy-Diagnostics-NIC/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Traffic_Manager_to_Log_Analytics_workspace_Deploy-Diagnostics-TrafficManager/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Virtual_Network_to_Log_Analytics_workspace_Deploy-Diagnostics-VirtualNetwork/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Virtual_Machines_to_Log_Analytics_workspace_Deploy-Diagnostics-VM/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Virtual_Machine_Scale_Sets_to_Log_Analytics_workspace_Deploy-Diagnostics-VMSS/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_VPN_Gateway_to_Log_Analytics_workspace_Deploy-Diagnostics-VNetGW/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_WVD_Application_group_to_Log_Analytics_workspace_Deploy-Diagnostics-WVDAppGroup/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_WVD_Host_Pools_to_Log_Analytics_workspace_Deploy-Diagnostics-WVDHostPools/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_WVD_Workspace_to_Log_Analytics_workspace_Deploy-Diagnostics-WVDWorkspace/**'
#      - 'policies/Deploy_Azure_Firewall_Manager_policy_in_the_subscription_Deploy-FirewallPolicy/**'
#      - 'policies/Deploys_NSG_flow_logs_and_traffic_analytics_Deploy-Nsg-FlowLogs/**'
#      - 'policies/Deploys_NSG_flow_logs_and_traffic_analytics_to_Log_Analytics_Deploy-Nsg-FlowLogs-to-LA/**'
#      - 'policies/Azure_Storage_deploy_a_specific_min_TLS_version_requirement_and_enforce_SSL/HTTPS_Deploy-Storage-sslEnforcement/**'
#      - 'policies/Deploy_Virtual_Network_with_peering_to_the_hub_Deploy-VNET-HubSpoke/**'
#      - .github/workflows/manage-azure-policy-6c2adb0d.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_6c2adb0d}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/KeyVault_SoftDelete_should_be_enabled_Append-KV-SoftDelete/**
          policies/Application_Gateway_should_be_deployed_with_WAF_enabled_Deny-AppGW-Without-WAF/**
          policies/Deny_the_creation_of_public_IP_Deny-PublicIP/**
          policies/RDP_access_from_the_Internet_should_be_blocked_Deny-RDP-From-Internet/**
          policies/Subnets_should_have_a_Network_Security_Group_Deny-Subnet-Without-Nsg/**
          policies/Subnets_should_have_a_User_Defined_Route_Deny-Subnet-Without-Udr/**
          policies/Deploy_a_default_budget_on_all_subscriptions_under_the_assigned_scope_Deploy-Budget/**
          policies/Deploy_a_route_table_with_specific_user_defined_routes_Deploy-Custom-Route-Table/**
          policies/Deploy_Diagnostic_Settings_for_Application_Gateway_to_Log_Analytics_workspace_Deploy-Diagnostics-ApplicationGateway/**
          policies/Deploy_Diagnostic_Settings_for_ExpressRoute_to_Log_Analytics_workspace_Deploy-Diagnostics-ExpressRoute/**
          policies/Deploy_Diagnostic_Settings_for_Firewall_to_Log_Analytics_workspace_Deploy-Diagnostics-Firewall/**
          policies/Deploy_Diagnostic_Settings_for_Load_Balancer_to_Log_Analytics_workspace_Deploy-Diagnostics-LoadBalancer/**
          policies/Deploy_Diagnostic_Settings_for_Network_Security_Groups_to_Log_Analytics_workspace_Deploy-Diagnostics-NetworkSecurityGroups/**
          policies/Deploy_Diagnostic_Settings_for_Network_Interfaces_to_Log_Analytics_workspace_Deploy-Diagnostics-NIC/**
          policies/Deploy_Diagnostic_Settings_for_Traffic_Manager_to_Log_Analytics_workspace_Deploy-Diagnostics-TrafficManager/**
          policies/Deploy_Diagnostic_Settings_for_Virtual_Network_to_Log_Analytics_workspace_Deploy-Diagnostics-VirtualNetwork/**
          policies/Deploy_Diagnostic_Settings_for_Virtual_Machines_to_Log_Analytics_workspace_Deploy-Diagnostics-VM/**
          policies/Deploy_Diagnostic_Settings_for_Virtual_Machine_Scale_Sets_to_Log_Analytics_workspace_Deploy-Diagnostics-VMSS/**
          policies/Deploy_Diagnostic_Settings_for_VPN_Gateway_to_Log_Analytics_workspace_Deploy-Diagnostics-VNetGW/**
          policies/Deploy_Diagnostic_Settings_for_WVD_Application_group_to_Log_Analytics_workspace_Deploy-Diagnostics-WVDAppGroup/**
          policies/Deploy_Diagnostic_Settings_for_WVD_Host_Pools_to_Log_Analytics_workspace_Deploy-Diagnostics-WVDHostPools/**
          policies/Deploy_Diagnostic_Settings_for_WVD_Workspace_to_Log_Analytics_workspace_Deploy-Diagnostics-WVDWorkspace/**
          policies/Deploy_Azure_Firewall_Manager_policy_in_the_subscription_Deploy-FirewallPolicy/**
          policies/Deploys_NSG_flow_logs_and_traffic_analytics_Deploy-Nsg-FlowLogs/**
          policies/Deploys_NSG_flow_logs_and_traffic_analytics_to_Log_Analytics_Deploy-Nsg-FlowLogs-to-LA/**
          policies/Azure_Storage_deploy_a_specific_min_TLS_version_requirement_and_enforce_SSL/HTTPS_Deploy-Storage-sslEnforcement/**
          policies/Deploy_Virtual_Network_with_peering_to_the_hub_Deploy-VNET-HubSpoke/**
